<?php
// phpcs:ignoreFile
/**
 * This file is generated by 10up-toolkit and copied into your dist folder, do not modifies this file directly.
 */
namespace TenUpToolkit;

if ( ! function_exists( __NAMESPACE__ . '\\set_dist_url_path' ) ) {
	$dist_url = false;
	$dist_path = false;

	function set_dist_url_path( $url, $path ) {
		global $dist_url, $dist_path;
		$dist_url = $url;
		$dist_path = $path;
	}
}

if ( ! function_exists( __NAMESPACE__ . '\\register_react_fast_refresh') ) {
	add_action( 'init', __NAMESPACE__ . '\\register_react_fast_refresh', 1 );

	/**
	 * Register React Fast Refresh scripts
	 *
	 * @return void
	 */
	function register_react_fast_refresh() {
		global $dist_url, $dist_path;

		if ( ! $dist_url || ! $dist_path ) {
			trigger_error( '10up-toolkit error: you must defined call TenUpToolkit\set_dist_url_path with the URL and path to dist folfer to get fast refresh to work' );
			return;
		}

		$react_fast_refresh_entry   = $dist_url . 'fast-refresh/react-refresh-entry/index.min.js';
		$react_fast_refresh_runtime = $dist_url . 'fast-refresh/react-refresh-runtime/index.min.js';
		$hmr_runtime                = $dist_url . 'fast-refresh/hmr-runtime.js';

		$react_fast_refresh_entry_path   = $dist_path . 'fast-refresh/react-refresh-entry/index.min.js';
		$react_fast_refresh_runtime_path = $dist_path . 'fast-refresh/react-refresh-runtime/index.min.js';
		$hmr_runtime_path                = $dist_path . 'fast-refresh/hmr-runtime.js';


		if (
			! file_exists( $react_fast_refresh_entry_path )
			|| ! file_exists( $react_fast_refresh_runtime_path )
			|| ! file_exists( $hmr_runtime_path )
		) {
			return;
		}

		wp_register_script(
			'tenup-toolkit-react-fast-refresh-entry',
			$react_fast_refresh_entry,
			[],
			filemtime( $react_fast_refresh_entry_path ),
		);

		wp_register_script(
			'tenup-toolkit-react-refresh-runtime',
			$react_fast_refresh_runtime,
			[],
			filemtime( $react_fast_refresh_runtime_path ),
		);

		wp_register_script(
			'tenup-toolkit-hmr-runtime',
			$hmr_runtime,
			[],
			filemtime( $react_fast_refresh_runtime_path ),
		);

		global $wp_scripts;
		$script = $wp_scripts->query( 'react', 'registered' );

		if ( $script ) {
			// remove default react-refresh-entry by default
			if ( in_array( 'wp-react-refresh-entry', $script->deps ) ) {
				unset( $script->deps[ array_search( 'wp-react-refresh-entry', $script->deps ) ] );
			}

			if( !in_array( 'tenup-toolkit-react-refresh-runtime', $script->deps ) ){
				$script->deps[] = 'tenup-toolkit-react-refresh-runtime';
			}

			if( !in_array( 'tenup-toolkit-react-fast-refresh-entry', $script->deps ) ){
				$script->deps[] = 'tenup-toolkit-react-fast-refresh-entry';
			}

			if( !in_array( 'tenup-toolkit-hmr-runtime', $script->deps ) ){
				$script->deps[] = 'tenup-toolkit-hmr-runtime';
			}
		}
	}
}


if ( ! function_exists( __NAMESPACE__  . '\\scripts', ) ) {
	add_action( 'wp_enqueue_scripts',  __NAMESPACE__  . '\\scripts', 1 );

	function scripts() {
		wp_enqueue_script( 'tenup-toolkit-react-refresh-runtime' );
		wp_enqueue_script( 'tenup-toolkit-hmr-runtime' );
	}
}

if ( ! function_exists( __NAMESPACE__  . '\\admin_scripts' ) ) {
	add_action( 'admin_enqueue_scripts',  __NAMESPACE__  . '\\admin_scripts', 1 );

	function admin_scripts() {
		wp_enqueue_script( 'tenup-toolkit-react-refresh-runtime' );
		wp_enqueue_script( 'tenup-toolkit-hmr-runtime' );
	}
}

