image: docker.10up.com/10up-build/deploy-container:latest

stages:
  - test-and-build
  - deploy

test_syntax:
  stage: test-and-build
  script:
    - php-syntax
  dependencies: []
  cache: {}

test_virusscan:
  stage: test-and-build
  script:
    - virus-scan
  dependencies: []
  cache: {}

build_plugins_and_themes:
  stage: test-and-build
  script:
    - bash "$build_script_path"
  artifacts:
    paths:
      - payload
    expire_in: 1 day
  dependencies: []
  cache: {}
  only:
    - $main_branch

deploy_trunk:
  stage: deploy
  environment:
    name: Production
    url: https://internal.10up.com
  script:
    - rsync -vrxc --delete --exclude-from=./deploy-scripts/rsync-excludes.txt ./payload/ gitlab@157.230.163.172:/var/www/demo.10up.com/wp-content/
  only:
    - $main_branch
