name: Publish a minor version to NPM
on:
  pull_request:
    branches:
      - 'minor-release'
    types: [closed]
concurrency: 
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install all npm packages
        run: npm ci
    
      - name: Configure git user name and email
        run: |
            git config user.name "10up Bot"
            git config user.email "pr@10up.com"
      - name: release
        run: |
          npx lerna publish minor --yes --no-verify-access --no-commit-hooks
        env:
           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}